"""empty message

Revision ID: 50baab560619
Revises: 13c589402a2e
Create Date: 2017-02-16 15:43:55.191345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50baab560619'
down_revision = '13c589402a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
